name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:  # Environment variable for debug logging (optional but helpful)
      ACTIONS_STEP_DEBUG: true

    steps:
      # Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Vercel CLI (if needed)
      - name: Install Vercel CLI
        run: npm install -g vercel

      # Step 3: Deploy to Vercel with automatic confirmation
      - name: Deploy to Vercel
        run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }} --yes
